name: Development Schema Drift Check

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  development:
    name: Check development schema
    uses: ./.github/workflows/check_schema_reusable.yaml
    with:
      gpp_env: development
      continue_on_error: false
      token_var: GPP_DEVELOPMENT_TOKEN
    secrets:
      token: ${{ secrets.GPP_DEVELOPMENT_TOKEN }}
